MiPlanilla/MiPlanilla.Web/Controllers/EmpleadoController.cs
using MiPlanilla.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiPlanilla.Web.Controllers
{
    public class EmpleadoController : Controller
    {
        // GET: Empleado
        public ActionResult Index()
        {

            var empleadoBL = new EmpleadoBL();
            var ListadeEmpleados = empleadoBL.Obtener();
            
            return View(ListadeEmpleados);
        }
    }
}

MiPlanilla/MiPlanilla.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MiPlanilla.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

MiPlanilla/MiPlanilla.Web/Views/Empleado/Index.cshtml
@model List<MiPlanilla.BL.Empleado>
@{
    ViewBag.Title = "Index";
}

<h2>Lista de Empleados</h2>

<table class="table table-bordered table-hover">

    <thead>
        <tr>
            <th>Id</th>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Salario</th>
            <th>Estatus</th>
            <th>Cargo</th>
            <th>FechaIngreso</th>
        </tr>

    </thead>

     @foreach (var empleado in Model)

     {
         <tr>
             <td>@empleado.Id</td>
             <td>@empleado.Nombres</td>
             <td>@empleado.Apellidos</td>
             <td>@empleado.Salario</td>
             <td>@empleado.Estatus</td>
             <td>@empleado.Cargo</td>
             <td>@empleado.FechaIngreso </td>

         </tr>
     }


</table>

MiPlanilla/MiPlanilla.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Bienvenido a Mi Planilla</h2>

MiPlanilla/MiPlanilla.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sistema de Planilla", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Inicio","index","Home")
                    </li>
                    <li>
                        @Html.ActionLink("Lista de Empleados ","Index","Empleado")

                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application MMEJIA</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>